INVITE sip:{{FUZZ}}alice{{/FUZZ}}@192.168.1.10 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.20:5060;branch=z9hG4bK-{{FUZZ}}776asdhds{{/FUZZ}}
Max-Forwards: {{FUZZ}}70{{/FUZZ}}
From: <sip:tester@192.168.1.20>;tag={{FUZZ}}1928301774{{/FUZZ}}
To: <sip:alice@192.168.1.10>
Call-ID: {{FUZZ}}a84b4c76e66710{{/FUZZ}}@192.168.1.20
CSeq: 314159 INVITE
Contact: <sip:tester@192.168.1.20>
Content-Type: application/sdp
Content-Length: 0

